#!/bin/bash
sudo apt install openssl 
mkdir ca
cd ca 
mkdir -p certs crl newcerts private subca/csr subca/certs
touch index.txt
touch index.txt.attr
echo '1000'>serial
echo '1000'>crlnumber
cd ..
cp rootca.cnf /home/pratham/ca
cd ca
openssl genrsa -aes256 -out private/ca.key.pem 4096
chmod 400 private/ca.key.pem
echo 'key generated'
openssl req -config rootca.cnf -key private/ca.key.pem -new -x509 -days 7300 -sha256 -extensions v3_ca -out certs/ca.cert.pem
chmod 444 certs/ca.cert.pem
echo 'go to subca'
