#!/bin/bash
openssl ca -config rootca.cnf  -extensions v3_intermediate_ca -days 3650 -notext -md sha256 -in subca/csr/subca.csr.pem  -out subca/certs/subca.cert.pem
scp subca/certs/subca.cert.pem  pratham@192.168.80.20:/home/pratham/subca/certs/
echo "got to subca to check for certificate"
